### ISSUE TITLE
Cosmos DB Schema not provided

### ISSUE THREAD

**Issue by tirumaesh** [victor-kironde/vk_reminder_bot#15]
Bot runs into error when started. Some issue with cosmos db connection and schema.

**Comment by victor-kironde** [comment]
Hi @tirumaesh 
I'm looking into this.

**Comment by victor-kironde** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cosmos Issue](https://trello.com/c/X7u1ymrB/93-cosmos-issue)
